import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono, Jersey_10, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Provider from "./provider";


const jetbrainsMono = JetBrains_Mono({subsets:['latin'],variable:'--font-mono'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const gameFont = Jersey_10({
  subsets: ['latin'],
  variable: "--font-game",
  weight: ['400']
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      suppressHydrationWarning
      lang="en"
      className={cn("h-full", "antialiased","dark", geistSans.variable, geistMono.variable, "font-mono", jetbrainsMono.variable, gameFont.variable, inter.variable)  }
    >
      <body className="min-h-full flex flex-col">
        <Provider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          enableColorScheme={false}
          disableTransitionOnChange
        >
          {children}
        </Provider>
      </body>
    </html>
  );
}
